name: Publish preview update

on:
  push:
    branches: ["preview"]

jobs:
  publish_preview_update:
    name: Publish preview update
    type: update
    params:
      channel: preview
      message: "Auto update: ${{ github.event.head_commit.message }}"
      branch: preview
